### PR TITLE
Fixed compilation of webserver example.

### PR DESCRIPTION
**Pull request by const-rs**
Webserver example does not compile without this tiny fix.

### CODE REVIEW

**Comment by kfl** [comment]
Thanks, nice catch.

(BTW, you might also be interested in <https://github.com/kfl/webserver-functor>)

**Comment by const-rs** [comment]
Thanks. Why don't you want to merge pull request with Size exception in Time?

**Comment by kfl** [comment]
I do want to merge PR #38, but since it is a change to a basic library module. I want to make sure that it doesn't break anything, and preferably add a unit test for it. Alas, I haven't had time to do that (or rather, when I've had time, I've forgotten.)

**Comment by const-rs** [comment]
Great! I actually was afraid that you have abandoned the project. I am currently writing a .mlb parser (mosmlb tool). It is almost correctly is parsing all MLton .mlb files. I'll send pull request not intended for merge today (for discussion).

**Comment by kfl** [comment]
In that case you might be interested in https://github.com/kfl/mosml/tree/master/src/mosmlpm which was my attempt at implementing a predecessor for .mlb files.

**Comment by const-rs** [comment]
Thanks! I used it as a start. :-)

**Pull request merged**
